INSERT INTO iam.permissions (code, description) VALUES
('base.tenant.create', 'Create tenants'),
('base.tenant.read', 'Read tenant information'),
('base.tenant.update', 'Update tenant information'),
('base.tenant.delete', 'Delete tenants'),
('base.tenant.delete.request', 'Request tenant deletion'),
('base.tenant.delete.approve', 'Approve tenant deletion'),

('base.building.create', 'Create buildings'),
('base.building.read', 'Read building information'),
('base.building.update', 'Update building information'),
('base.building.delete', 'Delete buildings'),
('base.building.delete.request', 'Request building deletion'),
('base.building.delete.approve', 'Approve building deletion'),

('base.unit.create', 'Create units'),
('base.unit.read', 'Read unit information'),
('base.unit.update', 'Update unit information'),
('base.unit.delete', 'Delete units'),
('base.unit.view', 'View units'),
('base.unit.status.manage', 'Manage unit status'),

('base.vehicle.create', 'Create vehicle records'),
('base.vehicle.read', 'Read vehicle information'),
('base.vehicle.update', 'Update vehicle information'),
('base.vehicle.delete', 'Delete vehicle records'),
('base.vehicle.view', 'View vehicles'),
('base.vehicle.status.manage', 'Manage vehicle status'),

('base.vehicle.registration.create', 'Create vehicle registration'),
('base.vehicle.registration.read', 'Read vehicle registration'),
('base.vehicle.registration.update', 'Update vehicle registration'),
('base.vehicle.registration.delete', 'Delete vehicle registration'),
('base.vehicle.registration.approve', 'Approve vehicle registration'),
('base.vehicle.registration.view', 'View vehicle registrations'),
('base.vehicle.registration.cancel', 'Cancel vehicle registration'),
('iam.user.create', 'Create users'),
('iam.user.read', 'Read user information'),
('iam.user.update', 'Update user information'),
('iam.user.delete', 'Delete users'),
('iam.user.activate', 'Activate/deactivate users'),

('iam.role.create', 'Create roles'),
('iam.role.read', 'Read role information'),
('iam.role.update', 'Update role information'),
('iam.role.delete', 'Delete roles'),
('iam.role.assign', 'Assign roles to users'),

('iam.permission.create', 'Create permissions'),
('iam.permission.read', 'Read permission information'),
('iam.permission.update', 'Update permission information'),
('iam.permission.delete', 'Delete permissions'),
('maintenance.request.create', 'Create maintenance requests'),
('maintenance.request.read', 'Read maintenance information'),
('maintenance.request.update', 'Update maintenance requests'),
('maintenance.request.delete', 'Delete maintenance requests'),
('maintenance.request.assign', 'Assign maintenance tasks'),
('maintenance.request.approve', 'Approve maintenance requests'),
('finance.read', 'Read financial information'),
('finance.update', 'Update financial records'),
('finance.delete', 'Delete financial records'),
('finance.create', 'Create financial records'),
('finance.approve', 'Approve financial transactions'),
('document.create', 'Create documents'),
('document.read', 'Read documents'),
('document.update', 'Update documents'),
('document.delete', 'Delete documents'),
('document.upload', 'Upload documents'),
('document.download', 'Download documents'),
('report.read', 'Read reports'),
('report.create', 'Create reports'),
('report.export', 'Export reports'),
('report.approve', 'Approve reports'),
('system.config', 'Configure system settings'),
('system.backup', 'Create system backups'),
('system.log', 'View system logs'),
('system.monitor', 'Monitor system health'),
('system.maintenance', 'Perform system maintenance')

ON CONFLICT (code) DO NOTHING;
