-- Admin role permissions (full access)
INSERT INTO iam.role_permissions (role, permission_code) VALUES
('admin', 'base.tenant.create'),
('admin', 'base.tenant.read'),
('admin', 'base.tenant.update'),
('admin', 'base.tenant.delete'),
('admin', 'base.tenant.delete.request'),
('admin', 'base.tenant.delete.approve'),
('admin', 'base.building.create'),
('admin', 'base.building.read'),
('admin', 'base.building.update'),
('admin', 'base.building.delete'),
('admin', 'base.building.delete.request'),
('admin', 'base.building.delete.approve'),
('admin', 'base.unit.create'),
('admin', 'base.unit.read'),
('admin', 'base.unit.update'),
('admin', 'base.unit.delete'),
('admin', 'base.unit.view'),
('admin', 'base.unit.status.manage'),
('admin', 'base.vehicle.create'),
('admin', 'base.vehicle.read'),
('admin', 'base.vehicle.update'),
('admin', 'base.vehicle.delete'),
('admin', 'base.vehicle.view'),
('admin', 'base.vehicle.status.manage'),
('admin', 'base.vehicle.registration.create'),
('admin', 'base.vehicle.registration.read'),
('admin', 'base.vehicle.registration.update'),
('admin', 'base.vehicle.registration.delete'),
('admin', 'base.vehicle.registration.approve'),
('admin', 'base.vehicle.registration.view'),
('admin', 'base.vehicle.registration.cancel'),
('admin', 'iam.user.create'),
('admin', 'iam.user.read'),
('admin', 'iam.user.update'),
('admin', 'iam.user.delete'),
('admin', 'iam.user.activate'),
('admin', 'iam.role.create'),
('admin', 'iam.role.read'),
('admin', 'iam.role.update'),
('admin', 'iam.role.delete'),
('admin', 'iam.role.assign'),
('admin', 'iam.permission.create'),
('admin', 'iam.permission.read'),
('admin', 'iam.permission.update'),
('admin', 'iam.permission.delete'),
('admin', 'maintenance.request.create'),
('admin', 'maintenance.request.read'),
('admin', 'maintenance.request.update'),
('admin', 'maintenance.request.delete'),
('admin', 'maintenance.request.assign'),
('admin', 'maintenance.request.approve'),
('admin', 'finance.read'),
('admin', 'finance.update'),
('admin', 'finance.delete'),
('admin', 'finance.create'),
('admin', 'finance.approve'),
('admin', 'document.create'),
('admin', 'document.read'),
('admin', 'document.update'),
('admin', 'document.delete'),
('admin', 'document.upload'),
('admin', 'document.download'),
('admin', 'report.read'),
('admin', 'report.create'),
('admin', 'report.export'),
('admin', 'report.approve'),
('admin', 'system.config'),
('admin', 'system.backup'),
('admin', 'system.log'),
('admin', 'system.monitor'),
('admin', 'system.maintenance');

-- Tenant Owner role permissions
INSERT INTO iam.role_permissions (role, permission_code) VALUES
('tenant_owner', 'base.tenant.read'),
('tenant_owner', 'base.tenant.update'),
('tenant_owner', 'base.building.read'),
('tenant_owner', 'base.building.update'),
('tenant_owner', 'base.unit.read'),
('tenant_owner', 'base.unit.view'),
('tenant_owner', 'base.unit.status.manage'),
('tenant_owner', 'base.vehicle.read'),
('tenant_owner', 'base.vehicle.view'),
('tenant_owner', 'base.vehicle.registration.read'),
('tenant_owner', 'base.vehicle.registration.view'),
('tenant_owner', 'maintenance.request.create'),
('tenant_owner', 'maintenance.request.read'),
('tenant_owner', 'maintenance.request.update'),
('tenant_owner', 'finance.read'),
('tenant_owner', 'document.read'),
('tenant_owner', 'document.upload'),
('tenant_owner', 'document.download'),
('tenant_owner', 'report.read'),
('tenant_owner', 'report.create'),
('tenant_owner', 'report.export');

-- Technician role permissions (device management)
INSERT INTO iam.role_permissions (role, permission_code) VALUES
('technician', 'base.unit.read'),
('technician', 'base.unit.view'),
('technician', 'base.unit.status.manage'),
('technician', 'base.vehicle.read'),
('technician', 'base.vehicle.view'),
('technician', 'base.vehicle.status.manage'),
('technician', 'maintenance.request.read'),
('technician', 'maintenance.request.update'),
('technician', 'maintenance.request.assign'),
('technician', 'maintenance.request.approve'),
('technician', 'document.read'),
('technician', 'document.upload'),
('technician', 'document.download'),
('technician', 'report.read'),
('technician', 'report.create');

-- Supporter role permissions (customer support)
INSERT INTO iam.role_permissions (role, permission_code) VALUES
('supporter', 'base.tenant.read'),
('supporter', 'base.building.read'),
('supporter', 'base.unit.read'),
('supporter', 'base.unit.view'),
('supporter', 'base.vehicle.read'),
('supporter', 'base.vehicle.view'),
('supporter', 'maintenance.request.create'),
('supporter', 'maintenance.request.read'),
('supporter', 'maintenance.request.update'),
('supporter', 'maintenance.request.assign'),
('supporter', 'document.read'),
('supporter', 'document.upload'),
('supporter', 'document.download'),
('supporter', 'report.read');

-- Account role permissions (basic access)
INSERT INTO iam.role_permissions (role, permission_code) VALUES
('account', 'base.tenant.read'),
('account', 'base.building.read'),
('account', 'base.unit.read'),
('account', 'base.unit.view'),
('account', 'base.vehicle.read'),
('account', 'base.vehicle.view'),
('account', 'maintenance.request.create'),
('account', 'maintenance.request.read'),
('account', 'document.read'),
('account', 'document.download'),
('account', 'report.read')

ON CONFLICT (role, permission_code) DO NOTHING;
